[project]
name = "k8s-thw-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "podman>=5.6.0",
    "requests>=2.32.5",
    "yaspin>=3.3.0",
]
